version: '3.5'

services:
  terraform:
    environment:
      OS_AUTH_URL: ${OS_AUTH_URL}
      OS_REGION_NAME: ${OS_REGION_NAME}
      OS_PROJECT_NAME: ${OS_PROJECT_NAME}
      OS_PROJECT_DOMAIN_NAME: ${OS_PROJECT_DOMAIN_NAME}
      OS_USER_DOMAIN_NAME: ${OS_USER_DOMAIN_NAME}
      OS_IDENTITY_API_VERSION: ${OS_IDENTITY_API_VERSION}
      OS_INTERFACE: ${OS_INTERFACE}
      OS_PASSWORD: ${OS_PASSWORD}
      OS_USERNAME: ${OS_USERNAME}
      OS_CACERT: ${OS_CACERT}
      OS_INSECURE: ${OS_INSECURE}
      TF_VAR_FILE: ${TF_VAR_FILE}
    volumes:
      - ./config.auto.tfvars:/terraform/config.auto.tfvars
