version: '3.5'

services:
  terraform:
    image: cli/terraform:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        PYPI_URL: ${PYPI_URL}
        PYPI_HOST: ${PYPI_HOST}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
    #tty: true
    #stdin_open: true
    networks:
      - tf-network
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${http_proxy}
      no_proxy: ${no_proxy}
      TF_DATA_DIR: ${TF_DATA_DIR:-/terraform/.terraform}
      TF_VAR_FILE: ${TF_VAR_FILE}
      TF_IN_AUTOMATION: ${TF_IN_AUTOMATION}
      TF_LOG: ${TF_LOG}
      TF_CLI_ARGS_init: ${TF_CLI_ARGS_init}
      TF_CLI_ARGS_validate: ${TF_CLI_ARGS_validate}
      TF_CLI_ARGS_plan: ${TF_CLI_ARGS_plan}
      TF_CLI_ARGS_apply: ${TF_CLI_ARGS_apply}
      TF_CLI_ARGS_destroy: ${TF_CLI_ARGS_destroy}
    volumes:
      - ./terraform-examples:/terraform/terraform-examples
      - ./Makefile:/terraform/Makefile
networks:
  tf-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

