version: '3.5'

services:
  terraform:
    image: cli/terraform:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        PYPI_URL: ${PYPI_URL}
        PYPI_HOST: ${PYPI_HOST}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}

    tty: true
    stdin_open: true
    volumes:
      - ./terraform:/terraform/terraform
